language: node_js
node_js:
- '5.0'
before_install:
- npm install babel-cli browserify mocha istanbul -g
install:
- npm install
script:
- ./ci/compile.js
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
